## Large Arrays

In [1]:
import urllib

local_fname = 'weather-buoy-data.txt.gz'
urllib.request.urlretrieve('https://www.ndbc.noaa.gov/data/historical/stdmet/42040h2021.txt.gz', local_fname)

# np.__version__
# !python -V
# iii
# !python4 -V

('weather-buoy-data.txt.gz', <http.client.HTTPMessage at 0x10835b010>)

In [2]:
import gzip

f = (gzip.open('weather-buoy-data.txt.gz'))
next(f)
next(f)
vals = []
for line in f:
    vals.append(float(line.split()[5]))


In [3]:
import numpy as np

orig = (vals[0] + (np.arange(len(vals)) % 10) / 11).reshape((16,2333))
# np.set_printoptions(edgeitems = 3)
# np.core.arrayprint._line_width = 180
# len("array([[88.     , 88.09091, 88.18182, 88.27273, ..., 88.81818, 88.     ")
orig

array([[88.        , 88.09090909, 88.18181818, ..., 88.        ,
        88.09090909, 88.18181818],
       [88.27272727, 88.36363636, 88.45454545, ..., 88.27272727,
        88.36363636, 88.45454545],
       [88.54545455, 88.63636364, 88.72727273, ..., 88.54545455,
        88.63636364, 88.72727273],
       ...,
       [88.81818182, 88.        , 88.09090909, ..., 88.81818182,
        88.        , 88.09090909],
       [88.18181818, 88.27272727, 88.36363636, ..., 88.18181818,
        88.27272727, 88.36363636],
       [88.45454545, 88.54545455, 88.63636364, ..., 88.45454545,
        88.54545455, 88.63636364]])

In [4]:
import numpy as np
a = np.round(orig, 2)
a

array([[88.  , 88.09, 88.18, ..., 88.  , 88.09, 88.18],
       [88.27, 88.36, 88.45, ..., 88.27, 88.36, 88.45],
       [88.55, 88.64, 88.73, ..., 88.55, 88.64, 88.73],
       ...,
       [88.82, 88.  , 88.09, ..., 88.82, 88.  , 88.09],
       [88.18, 88.27, 88.36, ..., 88.18, 88.27, 88.36],
       [88.45, 88.55, 88.64, ..., 88.45, 88.55, 88.64]])

In [5]:
b = np.floor(orig*100)/100
b

array([[88.  , 88.09, 88.18, ..., 88.  , 88.09, 88.18],
       [88.27, 88.36, 88.45, ..., 88.27, 88.36, 88.45],
       [88.54, 88.63, 88.72, ..., 88.54, 88.63, 88.72],
       ...,
       [88.81, 88.  , 88.09, ..., 88.81, 88.  , 88.09],
       [88.18, 88.27, 88.36, ..., 88.18, 88.27, 88.36],
       [88.45, 88.54, 88.63, ..., 88.45, 88.54, 88.63]])

In [6]:
c = np.delete(a, 5, 1)
c

array([[88.  , 88.09, 88.18, ..., 88.  , 88.09, 88.18],
       [88.27, 88.36, 88.45, ..., 88.27, 88.36, 88.45],
       [88.55, 88.64, 88.73, ..., 88.55, 88.64, 88.73],
       ...,
       [88.82, 88.  , 88.09, ..., 88.82, 88.  , 88.09],
       [88.18, 88.27, 88.36, ..., 88.18, 88.27, 88.36],
       [88.45, 88.55, 88.64, ..., 88.45, 88.55, 88.64]])

In [7]:
np.array_equal(a,c)

False

In [8]:
a.shape, b.shape, c.shape

((16, 2333), (16, 2333), (16, 2332))

## Real-Time Data

In [9]:
import urllib

local_fname = 'fl-weather-alerts.json'
urllib.request.urlretrieve('https://api.weather.gov/alerts/active?area=FL', local_fname)

('fl-weather-alerts.json', <http.client.HTTPMessage at 0x10835bf10>)

In [10]:
import json
d = json.load(open(local_fname));

In [11]:
len(d['features'])

18

In [12]:
[feat['properties']['headline'] for feat in d['features']]

['Rip Current Statement issued April 9 at 9:01PM EDT until April 13 at 3:00AM EDT by NWS Jacksonville FL',
 'Coastal Flood Advisory issued April 9 at 9:01PM EDT until April 12 at 5:00AM EDT by NWS Jacksonville FL',
 'High Surf Advisory issued April 9 at 9:01PM EDT until April 12 at 5:00AM EDT by NWS Jacksonville FL',
 'Coastal Flood Warning issued April 9 at 9:01PM EDT until April 11 at 5:00AM EDT by NWS Jacksonville FL',
 'Rip Current Statement issued April 9 at 7:15PM EDT until April 12 at 8:00AM EDT by NWS Miami FL',
 'Rip Current Statement issued April 9 at 7:15PM EDT until April 12 at 8:00AM EDT by NWS Miami FL',
 'High Surf Advisory issued April 9 at 7:15PM EDT until April 12 at 8:00AM EDT by NWS Miami FL',
 'High Surf Advisory issued April 9 at 7:15PM EDT until April 12 at 8:00AM EDT by NWS Miami FL',
 'Rip Current Statement issued April 9 at 2:41PM EDT until April 9 at 10:00PM EDT by NWS Tallahassee FL',
 'Wind Advisory issued April 9 at 2:00PM EDT until April 10 at 8:00PM EDT 