## Large Arrays

In [1]:
import urllib

local_fname = 'weather-buoy-data.txt.gz'
urllib.request.urlretrieve('https://www.ndbc.noaa.gov/data/historical/stdmet/42040h2021.txt.gz', local_fname)

# np.__version__
# !python -V
# iii
# !python4 -V

('weather-buoy-data.txt.gz', <http.client.HTTPMessage at 0x1054bea90>)

In [2]:
type((urllib.request.urlretrieve('https://www.ndbc.noaa.gov/data/historical/stdmet/42040h2021.txt.gz', local_fname)))


tuple

In [3]:
import gzip

f = (gzip.open('weather-buoy-data.txt.gz'))
next(f)
next(f)
vals = []
for line in f:
    vals.append(float(line.split()[5]))


In [4]:
import numpy as np

orig = (vals[0] + (np.arange(len(vals)) % 10) / 11).reshape((16,2333))
# np.set_printoptions(edgeitems = 3)
# np.core.arrayprint._line_width = 180
# len("array([[88.     , 88.09091, 88.18182, 88.27273, ..., 88.81818, 88.     ")
orig

array([[88.        , 88.09090909, 88.18181818, ..., 88.        ,
        88.09090909, 88.18181818],
       [88.27272727, 88.36363636, 88.45454545, ..., 88.27272727,
        88.36363636, 88.45454545],
       [88.54545455, 88.63636364, 88.72727273, ..., 88.54545455,
        88.63636364, 88.72727273],
       ...,
       [88.81818182, 88.        , 88.09090909, ..., 88.81818182,
        88.        , 88.09090909],
       [88.18181818, 88.27272727, 88.36363636, ..., 88.18181818,
        88.27272727, 88.36363636],
       [88.45454545, 88.54545455, 88.63636364, ..., 88.45454545,
        88.54545455, 88.63636364]])

In [5]:
type((orig))


numpy.ndarray

In [6]:
import numpy as np
a = np.round(orig, 2)
a

array([[88.  , 88.09, 88.18, ..., 88.  , 88.09, 88.18],
       [88.27, 88.36, 88.45, ..., 88.27, 88.36, 88.45],
       [88.55, 88.64, 88.73, ..., 88.55, 88.64, 88.73],
       ...,
       [88.82, 88.  , 88.09, ..., 88.82, 88.  , 88.09],
       [88.18, 88.27, 88.36, ..., 88.18, 88.27, 88.36],
       [88.45, 88.55, 88.64, ..., 88.45, 88.55, 88.64]])

In [7]:
type((a))


numpy.ndarray

In [8]:
b = np.floor(orig*100)/100
b

array([[88.  , 88.09, 88.18, ..., 88.  , 88.09, 88.18],
       [88.27, 88.36, 88.45, ..., 88.27, 88.36, 88.45],
       [88.54, 88.63, 88.72, ..., 88.54, 88.63, 88.72],
       ...,
       [88.81, 88.  , 88.09, ..., 88.81, 88.  , 88.09],
       [88.18, 88.27, 88.36, ..., 88.18, 88.27, 88.36],
       [88.45, 88.54, 88.63, ..., 88.45, 88.54, 88.63]])

In [9]:
type((b))


numpy.ndarray

In [10]:
c = np.delete(a, 5, 1)
c

array([[88.  , 88.09, 88.18, ..., 88.  , 88.09, 88.18],
       [88.27, 88.36, 88.45, ..., 88.27, 88.36, 88.45],
       [88.55, 88.64, 88.73, ..., 88.55, 88.64, 88.73],
       ...,
       [88.82, 88.  , 88.09, ..., 88.82, 88.  , 88.09],
       [88.18, 88.27, 88.36, ..., 88.18, 88.27, 88.36],
       [88.45, 88.55, 88.64, ..., 88.45, 88.55, 88.64]])

In [11]:
type((c))


numpy.ndarray

In [12]:
np.array_equal(a,c)

False

In [13]:
type((np.array_equal(a,c)))


bool

In [14]:
a.shape, b.shape, c.shape

((16, 2333), (16, 2333), (16, 2332))

In [15]:
type((a.shape, b.shape, c.shape))


tuple

## Real-Time Data

In [16]:
import urllib

local_fname = 'fl-weather-alerts.json'
urllib.request.urlretrieve('https://api.weather.gov/alerts/active?area=FL', local_fname)

('fl-weather-alerts.json', <http.client.HTTPMessage at 0x105fc6590>)

In [17]:
type((urllib.request.urlretrieve('https://api.weather.gov/alerts/active?area=FL', local_fname)))


tuple

In [18]:
import json
d = json.load(open(local_fname));

In [19]:
len(d['features'])

2

In [20]:
type((len(d['features'])))


int

In [21]:
[feat['properties']['headline'] for feat in d['features']]

['Beach Hazards Statement issued April 17 at 4:58AM EDT until April 18 at 4:00AM EDT by NWS Melbourne FL',
 'Rip Current Statement issued April 17 at 2:21AM EDT until April 17 at 8:00PM EDT by NWS Tallahassee FL']

In [22]:
type(([feat['properties']['headline'] for feat in d['features']]))


list