In [3]:
%%capture --no-stderr cap
#the above capture function only captures this cells output and doesnot let it print

def printing():
    print("Here is printing function")
printing()



In [4]:
def printing2():
    print("Here is printing2 function")
printing2()

Here is printing2 function


In [5]:
with open('capture.txt', "w") as f:
    f.write(cap.stdout)

In [12]:
import numpy as np

arr = np.array([[1.86,2.98,3.45,4.976], [5.098,6.12,7.091,8.65]])

In [13]:
arr

array([[1.86 , 2.98 , 3.45 , 4.976],
       [5.098, 6.12 , 7.091, 8.65 ]])

In [15]:
np.floor(arr*100)/100

array([[1.86, 2.98, 3.45, 4.97],
       [5.09, 6.12, 7.09, 8.65]])

In [17]:
arr2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
np.delete(arr2, 2, 1)

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

In [19]:
arr

array([[1.86 , 2.98 , 3.45 , 4.976],
       [5.098, 6.12 , 7.091, 8.65 ]])

In [21]:
d = {"a" : [{"aa":1, "bb" : 2, "cc" : 3, "dd": 4}]}

In [22]:
d["a"]

[{'aa': 1, 'bb': 2, 'cc': 3, 'dd': 4}]

In [24]:
d["a"][0]

{'aa': 1, 'bb': 2, 'cc': 3, 'dd': 4}